// ADR 0003 slice 1 acceptance gate: resolveRoute() changes no routing beyond
// the three permitted classes of difference listed below.
//
// The gate is LIVE (tests/fixtures/route-golden/live-gate.mjs has the full
// rules): the pre-ADR resolver, vendored byte for byte under
// fixtures/route-golden/reference/, is run against the CURRENT config next
// to the current resolveRoute(), over every shipped task type plus "no type"
// and an unknown type, crossed with every declared weight, kind and
// consequence (preset-equal values and departures alike), at a clock before
// and after the haiku retirement date. A table edit moves both sides alike,
// so a trial's reviewBy extended or a trial ended stays green; a change to the
// resolution logic does not. The only differences permitted are:
//   - restated preset (slice 1b): an explicit field equal to the preset keeps
//     the type's trial;
//   - floor after trial (ADR §9 slice 1 carve-out): a trial below the resolved
//     consequence's floor is lifted to exactly that floor;
//   - waived trial (0.29.2 "effort" track): a trial override carrying its own
//     honoured F5 waiver keeps its raw answer below the elevated floor, the
//     waiver recorded. Only the types in live-gate.mjs's WAIVED_TRIAL_TYPES
//     (integration) may take this class.
// Each is checked against the answer the ADR rule prescribes, computed from
// the config — not merely tolerated. Any other difference fails here: a data
// finding to report, not a fixture to regenerate.
//
// expected.json is the frozen record the reference was vetted against: what
// the baseline resolver returned on the baseline config, generated by
// generate.mjs from the pinned commit. The first two tests prove the vendored
// reference IS that resolver (sha256) and still reproduces that record.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { PLUGIN_ROOT, makeFixture } from './helpers.mjs';
import { buildCases, CLOCKS } from './fixtures/route-golden/cases.mjs';
import {
  REFERENCE_DIR, REFERENCE_FILES, sha256Text, stageResolver, atClock, compareLive, floorsFor, WAIVED_TRIAL_TYPES,
} from './fixtures/route-golden/live-gate.mjs';

// Hermetic BEFORE the first modelTiers() call: no per-machine override file.
const fx = makeFixture();
const ctx = await import('../hooks/lib/context.mjs');
const staged = [];
test.after(() => { for (const s of staged) s.cleanup(); fx.cleanup(); });

const GOLDEN_DIR = join(PLUGIN_ROOT, 'tests', 'fixtures', 'route-golden');
const golden = JSON.parse(readFileSync(join(GOLDEN_DIR, 'expected.json'), 'utf8'));
const read = (p) => readFileSync(p, 'utf8');
const REF_CONTEXT = read(join(REFERENCE_DIR, 'hooks', 'lib', 'context.mjs'));
const REF_CONFIG = read(join(REFERENCE_DIR, 'config', 'model-tiers.json'));
const CUR_CONTEXT = read(join(PLUGIN_ROOT, 'hooks', 'lib', 'context.mjs'));
const CUR_CONFIG = read(join(PLUGIN_ROOT, 'config', 'model-tiers.json'));
const plain = (v) => JSON.parse(JSON.stringify(v));

async function stage(contextSource, configText) {
  const s = await stageResolver({ contextSource, configText });
  staged.push(s);
  return s.mod;
}
// The live matrix adds a fractional weight (2.5: inside 1-5, no routing row);
// the frozen record's matrix is the one it was generated with.
const casesFor = (cfg, { frozen = false } = {}) => buildCases({
  typeNames: Object.keys(cfg.taskTypes || {}),
  kinds: Object.keys(cfg.taskKinds || {}),
  consequences: Object.keys(cfg.consequence || {}),
  extraWeights: frozen ? [] : [2.5],
});

test('the vendored reference is the pinned baseline resolver, byte for byte', () => {
  assert.ok(golden.source?.commitSubject && golden.source?.commitDate, 'fixture must name the baseline commit');
  for (const rel of REFERENCE_FILES) {
    const want = golden.source?.sha256?.[rel] || '';
    assert.match(want, /^[0-9a-f]{64}$/, `baseline sha256 for ${rel}`);
    assert.equal(sha256Text(join(REFERENCE_DIR, rel)), want, `reference/${rel} is not the baseline file — it must never be edited`);
  }
});

test('the vendored reference still reproduces the frozen record on the baseline config', async () => {
  const ref = await stage(REF_CONTEXT, REF_CONFIG);
  const cases = casesFor(ref.modelTiers(), { frozen: true });
  assert.deepEqual(golden.clocks, CLOCKS);
  assert.equal(golden.caseCount, cases.length * CLOCKS.length);
  const bad = [];
  CLOCKS.forEach((clock, ci) => {
    for (const c of cases) {
      const bar = c.key.indexOf('|');
      const row = golden.cases[c.key.slice(0, bar)]?.[c.key.slice(bar + 1)];
      const want = row ? golden.results[row[ci]] : undefined;
      const got = plain(atClock(clock, () => ref.resolveExpected(c.args)));
      if (JSON.stringify(got) !== JSON.stringify(want)) bad.push(`${clock} ${c.key}`);
    }
  });
  assert.deepEqual(bad.slice(0, 20), [], `${bad.length} cases differ from expected.json`);
});

// The live gate on the shipped resolver and the shipped config.
const cfg = ctx.modelTiers();
const cases = casesFor(cfg);

// What the config itself makes reachable, so the gate's own sanity checks
// follow the table instead of assuming today's trials (RC review R4: ending
// every trial used to fail the gate, and ending the explore trial threw).
//   restated        needs a trial: an explicit preset-equal field keeps it
//                   here, where the reference fell to the grid;
//   floorAfterTrial needs a trial below some consequence's floor, with no
//                   honoured waiver of its own (the matrix passes every
//                   consequence without departing);
//   waivedTrial     needs a trial below the elevated floor that DOES carry
//                   its own honoured F5 waiver, on a WAIVED_TRIAL_TYPES type
//                   (0.29.2 "effort" track).
const trialTypes = (c) => Object.entries(c.taskTypes || {})
  .filter(([, t]) => t && t.override && typeof t.weight === 'number').map(([n]) => n);
const isHonouredWaiver = (n, ov) => WAIVED_TRIAL_TYPES.includes(n) && ov.waivesFloor === 'elevated' && ov.source === 'operator-observed';
function reachableClasses(c) {
  const trials = trialTypes(c);
  const floorAfterTrial = trials.some((n) => {
    const ov = c.taskTypes[n].override;
    if (isHonouredWaiver(n, ov)) return false; // that type's own gap is waivedTrial, not this class
    return Object.keys(c.consequence || {}).some((k) => {
      const f = floorsFor(c, k, ov.model, ov.effort || '');
      return f.model !== ov.model || f.effort !== (ov.effort || '');
    });
  });
  const waivedTrial = trials.some((n) => {
    const ov = c.taskTypes[n].override;
    if (!isHonouredWaiver(n, ov)) return false;
    const f = floorsFor(c, 'elevated', ov.model, ov.effort || '');
    return f.model !== ov.model || f.effort !== (ov.effort || '');
  });
  return { restated: trials.length > 0, floorAfterTrial, waivedTrial };
}

test(`LIVE: resolveRoute matches the frozen reference on the current config, all ${cases.length} cases x ${CLOCKS.length} clocks, differing only by the permitted classes`, async (t) => {
  const ref = await stage(REF_CONTEXT, CUR_CONFIG);
  const { mismatches, counts } = compareLive({ cur: ctx, ref, cfg, cases, clocks: CLOCKS });
  t.diagnostic(`classes: ${JSON.stringify(counts)}`);
  assert.deepEqual(mismatches.slice(0, 20), [], `${mismatches.length} mismatches — a resolver regression, or a shipped trial a floor refuses; report it`);
  assert.equal(counts.cases, cases.length * CLOCKS.length);
  // Every class the table makes reachable must be exercised; an empty one
  // would mean the gate stopped reaching it, not that the difference went
  // away. A table with no trials (every trial ended) has neither class.
  const reach = reachableClasses(cfg);
  if (reach.restated) assert.ok(counts.restated > 0, JSON.stringify(counts));
  if (reach.floorAfterTrial) assert.ok(counts.floorAfterTrial > 0, JSON.stringify(counts));
  if (reach.waivedTrial) assert.ok(counts.waivedTrial > 0, JSON.stringify(counts));
});

// --- The gate is not vacuous -------------------------------------------------
// Routine table edits keep it green; seeded resolver regressions turn it red.
// Each variant stages the CURRENT resolver (edited or not) and the reference
// against the same (edited or not) config.

async function gateOn(contextSource, configText) {
  const cfgV = JSON.parse(configText);
  const [cur, ref] = [await stage(contextSource, configText), await stage(REF_CONTEXT, configText)];
  return compareLive({ cur, ref, cfg: cur.modelTiers(), cases: casesFor(cfgV), clocks: CLOCKS });
}
// The self-tests below need trials to edit and to regress. When the shipped
// table has none (every trial ended), synthetic ones are added to a copy for
// the self-tests only — one below the elevated floor, one routine — so the
// seeded regressions stay detectable whatever the table carries.
function withTrials(text) {
  const c = JSON.parse(text);
  if (trialTypes(c).length >= 2) return text;
  const numeric = Object.entries(c.taskTypes || {}).filter(([, t]) => typeof t.weight === 'number' && !t.override);
  const pick = (want) => numeric.find(([, t]) => (t.consequence || 'routine') === want)?.[0];
  const names = [...new Set([pick('elevated'), pick('routine'), ...numeric.map(([n]) => n)].filter(Boolean))].slice(0, 2 - trialTypes(c).length);
  for (const n of names) {
    c.taskTypes[n].override = {
      model: 'opus', effort: 'low', reason: 'synthetic trial for the gate self-tests',
      evidence: { source: 'synthetic', date: '2026-01-01' }, trialSince: '2026-01-01', reviewBy: '2099-12-31',
    };
  }
  return JSON.stringify(c, null, 2);
}
const BASE_CONFIG = withTrials(CUR_CONFIG);
const edit = (fn) => { const c = JSON.parse(BASE_CONFIG); fn(c); return JSON.stringify(c, null, 2); };
// Targets come from the table, never hard-coded type names.
const [TRIAL_A, TRIAL_B] = (() => { const t = trialTypes(JSON.parse(BASE_CONFIG)); return [t[0], t[1] ?? t[0]]; })();
const GRID_ROW = Object.keys(JSON.parse(BASE_CONFIG).routing || {})[0];
function otherEffort(c, model, current) {
  const list = c.tiers?.[model]?.efforts || [];
  return list.find((e) => e !== current) ?? current;
}
const TRIAL_EDITS = {
  "extend a trial's reviewBy": (c) => { c.taskTypes[TRIAL_A].override.reviewBy = '2099-12-31'; },
  'end a trial (delete its override)': (c) => { delete c.taskTypes[TRIAL_B].override; },
  'end every trial': (c) => { for (const t of Object.values(c.taskTypes)) delete t.override; },
  'retune a trial': (c) => { const ov = c.taskTypes[TRIAL_A].override; ov.effort = otherEffort(c, ov.model, ov.effort); },
  'bump the table version': (c) => { c.version = (c.version || 0) + 1; },
  'move a grid row': (c) => { const r = c.routing[GRID_ROW]; c.routing[GRID_ROW] = { ...r, effort: otherEffort(c, r.model, r.effort) }; },
};
for (const [name, fn] of Object.entries(TRIAL_EDITS)) {
  test(`gate stays green on a routine table edit: ${name}`, async () => {
    const { mismatches } = await gateOn(CUR_CONTEXT, edit(fn));
    assert.deepEqual(mismatches.slice(0, 10), [], `${mismatches.length} mismatches`);
  });
}

// [anchor in hooks/lib/context.mjs, replacement]. Each anchor must exist
// exactly once, so a refactor that moves one fails loudly here instead of
// silently mutating nothing.
const REGRESSIONS = {
  'a departure no longer skips the trial': ['  if (ov) {\n    if (!asIs) {', '  if (ov) {\n    if (false) {'],
  'floors no longer run after the winning layer': ['  if (cons.effortFloor) {\n    const raised = raiseEffort(', '  if (false) {\n    const raised = raiseEffort('],
  "the grid ignores the kind's effort delta": ['const delta = (cfg.taskKinds || {})[kind]?.effortDelta ?? 0;', 'const delta = 0;'],
  'a preset-equal weight counts as a departure again': ["note('weight', weightExplicit, typeKnown && weight === t.weight);", "note('weight', weightExplicit, false);"],
  'the retirement date ignores the pinned clock': ['const n = clockDate(now);', 'const n = new Date(Date.parse(\'2026-09-24T12:00:00Z\'));'],
  'a weight with no routing row is a grid "winner" again': ['  if (!won && !grid.model) {', '  if (false) {'],
  'the trial answers with the grid model':['          model: ov.model,\n', '          model: grid.model,\n'],
};
for (const [name, [anchor, repl]] of Object.entries(REGRESSIONS)) {
  test(`gate goes red on a seeded resolver regression: ${name}`, async () => {
    assert.equal(CUR_CONTEXT.split(anchor).length, 2, `anchor for "${name}" must occur exactly once in context.mjs`);
    const { mismatches } = await gateOn(CUR_CONTEXT.replace(anchor, repl), BASE_CONFIG);
    assert.ok(mismatches.length > 0, 'the seeded regression passed the gate');
  });
}

test('the golden matrix exercises every layer outcome it should', () => {
  // A guard against a matrix that silently stops reaching a branch.
  const seen = new Set();
  for (const c of cases) {
    const r = ctx.resolveRoute({ ...c.args, now: CLOCKS[0] });
    seen.add(r.layer);
    if (r.skipped.some((s) => s.layer === 'trial')) seen.add('trial-skipped');
  }
  const outcomes = trialTypes(cfg).length ? ['trial', 'grid', null, 'trial-skipped'] : ['grid', null];
  for (const want of outcomes) assert.ok(seen.has(want), `no case reached ${want}`);
  // And the retirement clock really changes something (weight 1-2 grid rows).
  const a = ctx.resolveRoute({ weight: 1, weightExplicit: true, now: CLOCKS[0] });
  const b = ctx.resolveRoute({ weight: 1, weightExplicit: true, now: CLOCKS[1] });
  assert.notEqual(`${a.model}/${a.effort}`, `${b.model}/${b.effort}`, 'the post-retirement clock no longer exercises the staged replacement');
});
