// ADR 0003 slice 1 acceptance gate: resolveRoute() changes no routing beyond
// the two differences slice 1 decided on.
//
// The gate is LIVE (tests/fixtures/route-golden/live-gate.mjs has the full
// rules): the pre-ADR resolver, vendored byte for byte under
// fixtures/route-golden/reference/, is run against the CURRENT config next
// to the current resolveRoute(), over every shipped task type plus "no type"
// and an unknown type, crossed with every declared weight, kind and
// consequence (preset-equal values and departures alike), at a clock before
// and after the haiku retirement date. A table edit moves both sides alike,
// so a trial's reviewBy extended or a trial ended stays green; a change to the
// resolution logic does not. The only differences permitted are:
//   - restated preset (slice 1b): an explicit field equal to the preset keeps
//     the type's trial;
//   - floor after trial (ADR §9 slice 1 carve-out): a trial below the resolved
//     consequence's floor is lifted to exactly that floor.
// Each is checked against the answer the ADR rule prescribes, computed from
// the config — not merely tolerated. Any other difference fails here: a data
// finding to report, not a fixture to regenerate.
//
// expected.json is the frozen record the reference was vetted against: what
// the baseline resolver returned on the baseline config, generated by
// generate.mjs from the pinned commit. The first two tests prove the vendored
// reference IS that resolver (sha256) and still reproduces that record.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { PLUGIN_ROOT, makeFixture } from './helpers.mjs';
import { buildCases, CLOCKS } from './fixtures/route-golden/cases.mjs';
import {
  REFERENCE_DIR, REFERENCE_FILES, sha256Text, stageResolver, atClock, compareLive,
} from './fixtures/route-golden/live-gate.mjs';

// Hermetic BEFORE the first modelTiers() call: no per-machine override file.
const fx = makeFixture();
const ctx = await import('../hooks/lib/context.mjs');
const staged = [];
test.after(() => { for (const s of staged) s.cleanup(); fx.cleanup(); });

const GOLDEN_DIR = join(PLUGIN_ROOT, 'tests', 'fixtures', 'route-golden');
const golden = JSON.parse(readFileSync(join(GOLDEN_DIR, 'expected.json'), 'utf8'));
const read = (p) => readFileSync(p, 'utf8');
const REF_CONTEXT = read(join(REFERENCE_DIR, 'hooks', 'lib', 'context.mjs'));
const REF_CONFIG = read(join(REFERENCE_DIR, 'config', 'model-tiers.json'));
const CUR_CONTEXT = read(join(PLUGIN_ROOT, 'hooks', 'lib', 'context.mjs'));
const CUR_CONFIG = read(join(PLUGIN_ROOT, 'config', 'model-tiers.json'));
const plain = (v) => JSON.parse(JSON.stringify(v));

async function stage(contextSource, configText) {
  const s = await stageResolver({ contextSource, configText });
  staged.push(s);
  return s.mod;
}
const casesFor = (cfg) => buildCases({
  typeNames: Object.keys(cfg.taskTypes || {}),
  kinds: Object.keys(cfg.taskKinds || {}),
  consequences: Object.keys(cfg.consequence || {}),
});

test('the vendored reference is the pinned baseline resolver, byte for byte', () => {
  assert.ok(golden.source?.commitSubject && golden.source?.commitDate, 'fixture must name the baseline commit');
  for (const rel of REFERENCE_FILES) {
    const want = golden.source?.sha256?.[rel] || '';
    assert.match(want, /^[0-9a-f]{64}$/, `baseline sha256 for ${rel}`);
    assert.equal(sha256Text(join(REFERENCE_DIR, rel)), want, `reference/${rel} is not the baseline file — it must never be edited`);
  }
});

test('the vendored reference still reproduces the frozen record on the baseline config', async () => {
  const ref = await stage(REF_CONTEXT, REF_CONFIG);
  const cases = casesFor(ref.modelTiers());
  assert.deepEqual(golden.clocks, CLOCKS);
  assert.equal(golden.caseCount, cases.length * CLOCKS.length);
  const bad = [];
  CLOCKS.forEach((clock, ci) => {
    for (const c of cases) {
      const bar = c.key.indexOf('|');
      const row = golden.cases[c.key.slice(0, bar)]?.[c.key.slice(bar + 1)];
      const want = row ? golden.results[row[ci]] : undefined;
      const got = plain(atClock(clock, () => ref.resolveExpected(c.args)));
      if (JSON.stringify(got) !== JSON.stringify(want)) bad.push(`${clock} ${c.key}`);
    }
  });
  assert.deepEqual(bad.slice(0, 20), [], `${bad.length} cases differ from expected.json`);
});

// The live gate on the shipped resolver and the shipped config.
const cfg = ctx.modelTiers();
const cases = casesFor(cfg);

test(`LIVE: resolveRoute matches the frozen reference on the current config, all ${cases.length} cases x ${CLOCKS.length} clocks, differing only by the permitted classes`, async (t) => {
  const ref = await stage(REF_CONTEXT, CUR_CONFIG);
  const { mismatches, counts } = compareLive({ cur: ctx, ref, cfg, cases, clocks: CLOCKS });
  t.diagnostic(`classes: ${JSON.stringify(counts)}`);
  assert.deepEqual(mismatches.slice(0, 20), [], `${mismatches.length} mismatches — a resolver regression, or a shipped trial a floor refuses; report it`);
  assert.equal(counts.cases, cases.length * CLOCKS.length);
  // Both classes are reachable on the shipped table (it carries trials at
  // opus/low and elevated-preset types); an empty class would mean the gate
  // stopped exercising it, not that the difference went away.
  assert.ok(counts.restated > 0 && counts.floorAfterTrial > 0, JSON.stringify(counts));
});

// --- The gate is not vacuous -------------------------------------------------
// Routine table edits keep it green; seeded resolver regressions turn it red.
// Each variant stages the CURRENT resolver (edited or not) and the reference
// against the same (edited or not) config.

async function gateOn(contextSource, configText) {
  const cfgV = JSON.parse(configText);
  const [cur, ref] = [await stage(contextSource, configText), await stage(REF_CONTEXT, configText)];
  return compareLive({ cur, ref, cfg: cur.modelTiers(), cases: casesFor(cfgV), clocks: CLOCKS });
}
const edit = (fn) => { const c = JSON.parse(CUR_CONFIG); fn(c); return JSON.stringify(c, null, 2); };
const TRIAL_EDITS = {
  "extend a trial's reviewBy": (c) => { c.taskTypes.explore.override.reviewBy = '2026-10-14'; },
  'end a trial (delete its override)': (c) => { delete c.taskTypes.verify.override; },
  'end every trial': (c) => { for (const t of Object.values(c.taskTypes)) delete t.override; },
  'retune a trial': (c) => { c.taskTypes['debug-root-cause'].override.effort = 'medium'; },
  'bump the table version': (c) => { c.version = (c.version || 0) + 1; },
  'move a grid row': (c) => { c.routing['3'] = { ...c.routing['3'], effort: 'high' }; },
};
for (const [name, fn] of Object.entries(TRIAL_EDITS)) {
  test(`gate stays green on a routine table edit: ${name}`, async () => {
    const { mismatches } = await gateOn(CUR_CONTEXT, edit(fn));
    assert.deepEqual(mismatches.slice(0, 10), [], `${mismatches.length} mismatches`);
  });
}

// [anchor in hooks/lib/context.mjs, replacement]. Each anchor must exist
// exactly once, so a refactor that moves one fails loudly here instead of
// silently mutating nothing.
const REGRESSIONS = {
  'a departure no longer skips the trial': ['  if (ov) {\n    if (!asIs) {', '  if (ov) {\n    if (false) {'],
  'floors no longer run after the winning layer': ['  if (cons.effortFloor) {\n    const raised = raiseEffort(', '  if (false) {\n    const raised = raiseEffort('],
  "the grid ignores the kind's effort delta": ['const delta = (cfg.taskKinds || {})[kind]?.effortDelta ?? 0;', 'const delta = 0;'],
  'a preset-equal weight counts as a departure again': ["note('weight', weightExplicit, typeKnown && weight === t.weight);", "note('weight', weightExplicit, false);"],
  'the retirement date ignores the pinned clock': ['const n = clockDate(now);', 'const n = new Date(Date.parse(\'2026-09-24T12:00:00Z\'));'],
  'the trial answers with the grid model': ['          model: ov.model,\n', '          model: grid.model,\n'],
};
for (const [name, [anchor, repl]] of Object.entries(REGRESSIONS)) {
  test(`gate goes red on a seeded resolver regression: ${name}`, async () => {
    assert.equal(CUR_CONTEXT.split(anchor).length, 2, `anchor for "${name}" must occur exactly once in context.mjs`);
    const { mismatches } = await gateOn(CUR_CONTEXT.replace(anchor, repl), CUR_CONFIG);
    assert.ok(mismatches.length > 0, 'the seeded regression passed the gate');
  });
}

test('the golden matrix exercises every layer outcome it should', () => {
  // A guard against a matrix that silently stops reaching a branch.
  const seen = new Set();
  for (const c of cases) {
    const r = ctx.resolveRoute({ ...c.args, now: CLOCKS[0] });
    seen.add(r.layer);
    if (r.skipped.some((s) => s.layer === 'trial')) seen.add('trial-skipped');
  }
  for (const want of ['trial', 'grid', null, 'trial-skipped']) assert.ok(seen.has(want), `no case reached ${want}`);
  // And the retirement clock really changes something (weight 1-2 grid rows).
  const a = ctx.resolveRoute({ weight: 1, weightExplicit: true, now: CLOCKS[0] });
  const b = ctx.resolveRoute({ weight: 1, weightExplicit: true, now: CLOCKS[1] });
  assert.notEqual(`${a.model}/${a.effort}`, `${b.model}/${b.effort}`, 'the post-retirement clock no longer exercises the staged replacement');
});
